-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Hôte : 127.0.0.1
-- Généré le : lun. 07 nov. 2022 à 08:53
-- Version du serveur : 10.4.24-MariaDB
-- Version de PHP : 8.1.6

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données : `playgames`
--

-- --------------------------------------------------------

--
-- Structure de la table `repertoire`
--

CREATE TABLE `repertoire` (
  `id` int(11) NOT NULL,
  `titre` char(60) DEFAULT NULL,
  `genre` char(60) DEFAULT NULL,
  `plateforme` char(60) DEFAULT NULL,
  `sortie` char(60) DEFAULT NULL,
  `synopsis` text DEFAULT NULL,
  `lien` text DEFAULT NULL,
  `fichier` text DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Déchargement des données de la table `repertoire`
--

INSERT INTO `repertoire` (`id`, `titre`, `genre`, `plateforme`, `sortie`, `synopsis`, `lien`, `fichier`) VALUES
(8, 'Call of Duty: Modern Warfare 2', 'action', 'Playstation, Xbox &amp; PC', '28/10/22', 'Call of Duty: Modern Warfare 2 se d&eacute;roule 5 ans apr&egrave;s les &eacute;v&eacute;nements du premier Modern Warfare, lesquels sont cens&eacute;s se d&eacute;rouler en 2011. La Russie serait en pleine guerre civile : loyalistes contre ultra-nationalistes. En m&ecirc;me temps au Moyen-Orient, un coup d&#039;&eacute;tat men&eacute; par un mouvement anti-occidental aurait eu lieu.\r\n', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/YH0q4kTWdcs\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>', 'cod.jpg'),
(9, 'Rainbow Six: Extraction', 'action', 'Playstation, Xbox &amp; PC', '28/01/22', 'Rainbow Six Extraction est un jeu multijoueur coop&eacute;ratif pouvant supporter jusqu&#039;&agrave; trois joueurs. Dans Extraction, les agents doivent infiltrer un endroit infest&eacute; d&#039;extraterrestres et atteindre des objectifs, tels que collecter des &eacute;chantillons, extraire des mat&eacute;riaux d&#039;ordinateurs et collecter des informations.\r\n', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/m0bSkYzXxKw\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>', 'rainbow.png'),
(10, 'Horizon: Forbidden West', 'action', 'Playstation', '18/02/22', 'Horizon Forbidden West continue l&#039;histoire d&#039;Aloy, une jeune chasseresse de la tribu Nora envoy&eacute;e en qu&ecirc;te d&#039;une myst&eacute;rieuse fronti&egrave;re s&#039;&eacute;tendan de l&#039;Utah jusqu&#039;&agrave; la c&ocirc;te Pacifique pour trouver la source d&#039;un myst&eacute;rieux fl&eacute;au qui tue tout ce qu&#039;il infecte.\r\n', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/Xk-xq6_Lr6E\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>', 'horizon.jpg'),
(11, 'Fortnite', 'action', 'Playstation, Xbox &amp; PC', '21/07/17', 'Fortnite Battle Royale est un jeu de battle royale &laquo; joueur contre joueur &raquo; avec un maximum de 100 joueurs, jouant seul, en &eacute;quipe de deux, de trois ou &agrave; quatre. Les joueurs sont largu&eacute;s dans un Bus de Combat qui traverse la carte du jeu sans aucune arme.\r\n', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/sig5I965rXs\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>', 'fortnite.jpg'),
(12, 'Gotham Knigth', 'action', 'Playstation, Xbox &amp; PC', '21/10/22', 'A la suite du meurtre de Bruce Wayne, son fils adoptif rebelle d&eacute;cide de former une alliance improbable avec les enfants des ennemis de Batman, qui sont tous suspect&eacute;s du meurtre du Chevalier Noir.\r\n', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/Twhx83W7tvI\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>', 'gotham.jpg'),
(13, 'Overwatch 2', 'action', 'Playstation, Xbox &amp; PC', '04/10/22', 'Le jeu propose un nouveau mode de jeu, Avanc&eacute;e (Push dans lequel les deux &eacute;quipes s&#039;affrontent afin de d&eacute;bloquer un robot et de l&#039;escorter jusqu&#039;&agrave; la base ennemie.\r\n', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/pyS3vmnWTyU\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>', 'overwatch.jpeg'),
(14, 'Cyberpunk: Phantom Liberty', 'aventure', 'Playstation, Xbox &amp; PC', '2023', 'Phantom Liberty, premi&egrave;re extension de Cyberpunk 2077, est enfin officialis&eacute; apr&egrave;s des mois de rumeurs. Elle permettra de s&#039;aventurer dans une zone in&eacute;dite de Night City, la ville embl&eacute;matique de cet univers futuriste. Pacifica est une v&eacute;ritable zone de non-droit, o&ugrave; l&#039;anarchie r&egrave;gne et o&ugrave; la violence est omnipr&eacute;sente.\r\n', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/BX2KE4KQ-t0\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>', 'cyberpunk.jpg'),
(15, 'Hogwarts: Legacy', 'aventure', 'Playstation, Xbox &amp; PC', '10/02/23', 'Hogwarts Legacy est un jeu de r&ocirc;le (RPG) d&#039;action-aventure en monde ouvert. Il se joue en mode solo et en vision objective. La personne qui joue peut choisir son genre, son apparence et sa maison de Poudlard, et progresse dans le jeu en &eacute;tant &eacute;quip&eacute;e d&#039;une baguette magique.\r\n', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/7slKny00ZIU\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>', 'hogwarts.jpg'),
(16, 'Final Fantasy VII: Rebirth', 'aventure', 'Playstation', '4èmeT 2023', '\r\nL&#039;histoire prend place dans la m&eacute;tropole cyberpunk, steampunk et dystopique6 de Midgar, les joueurs prennent le contr&ocirc;le du mercenaire Cloud Strife tandis que lui et un groupe &eacute;co-terroriste connu sous le nom d&#039;AVALANCHE s&#039;opposent &agrave; la Shinra Electric Power Company, une puissante entreprise, qui utilise l&#039;essence de la vie de la plan&egrave;te (mako) comme source d&#039;&eacute;nergie.\r\n', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/MHV7a8RM75k\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>', 'ff7.webp'),
(17, 'The Lord of The Rings: Return to Moria', 'aventure', 'Playstation, Xbox &amp; PC', '2023', 'Le Seigneur des Anneaux : Retour dans la Moria suit les Nains alors qu&#039;ils se lancent dans une nouvelle aventure pour reconqu&eacute;rir leur demeure l&eacute;gendaire de la Moria sous les Monts Brumeux. Les joueurs uniront leurs forces pour survivre, fabriquer, construire et explorer les mines embl&eacute;matiques et tentaculaires. Les explorateurs courageux devront &ecirc;tre vigilants car de myst&eacute;rieux dangers les attendent.\r\n', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/R6X2Ph8mdJI\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>', 'lotr.png'),
(18, 'Sonic Frontiers', 'aventure', 'Playstation, Xbox &amp; PC', '08/11/22', 'L&#039;histoire commence lorsque Sonic, Miles Tails Prower et Amy Rose sont aspir&eacute;s par un trou de ver et que Sonic est perdu sur une &icirc;le myst&eacute;rieuse, s&eacute;par&eacute;e de Tails et Amy. Une intelligence artificielle guide le joueur alors qu&#039;il cherche &agrave; collecter les Chaos Emeralds et &agrave; trouver les amis de Sonic.\r\n', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/83G8QRCduzg\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>', 'sonic.jpg'),
(19, 'Star Wars: Jedi Survivor', 'aventure', 'Playstation, Xbox &amp; PC', '2023', 'La suite de Satr Wars Jedi : Fallen Order mettra les joueurs une nouvelle fois aux commandes de Cal Kestis, dans un aventure plus sombre et violente. ', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/o7aBLD4YacY\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>', 'starwars.webp'),
(20, 'Blazing Strike', 'combat', 'Playstation, Xbox &amp; PC', '2023', 'Con&ccedil;u par le studio RareBreed Makes Games pour Aksys Games, ce titre offre des m&eacute;caniques dignes des jeux de combat d&#039;aujourd&#039;hui tout en misant sur un rendu pixel art. Blazing Strike est un jeu de combat qui se repose sur une prise en main &agrave; quatre boutons mais six variantes de coups (faible, moyen, fort) et trois options en d&eacute;fense - blocage, garde et parade.\r\n', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/6ldsWPI_48A\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>', 'blazing.jpg'),
(21, 'King Of Fighters XV', 'combat', 'Playstation, Xbox &amp; PC', '17/02/22', 'Iori Yagami &eacute;tant dans un tunnel est montr&eacute; hant&eacute; par les apparitions de ses anciennes comparses Vice et Mature. Ces derni&egrave;res font r&eacute;f&eacute;rence &agrave; ce qu&#039;il s&#039;est pass&eacute; dans l&#039;&eacute;pisode 14, &agrave; savoir la d&eacute;faite de Verse ayant provoqu&eacute; la lib&eacute;ration d&#039;&acirc;mes pouvant revenir sur Terre\r\n', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/7UbllmNKccc\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>', 'kingsof.jpg'),
(22, 'Midnight Fight Express', 'combat', 'Playstation, Xbox &amp; PC', '23/08/22', 'Billy Hayes, un simple voyageur, est arr&ecirc;t&eacute; en Turquie avec deux kilos de drogue sur lui. Le gouvernement souhaitant donner l&#039;exemple, l&#039;homme est condamn&eacute; &agrave; perp&eacute;tuit&eacute; et commence alors son douloureux p&eacute;riple &agrave; travers les prisons turques.\r\n', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/6OCsN9Z3JSg\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>', 'midnight.jpg'),
(23, 'MultiVersus', 'combat', 'Playstation, Xbox &amp; PC', '15/08/22', 'MultiVersus est un jeu de plateforme qui vous permet de faire &eacute;quipe avec vos amis en utilisant certains des personnages les plus embl&eacute;matiques comme Batman, Sammy et bien d&#039;autres. Trouvez vos combos de combat pr&eacute;f&eacute;r&eacute;s et sauvez le Multivers\r\n', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/k78vnMafjHQ\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>', 'multi.jpg'),
(24, 'Street Fighter 6', 'combat', 'Playstation, Xbox &amp; PC', '2023', 'Contrairement aux &eacute;pisodes pr&eacute;c&eacute;dents, ce sixi&egrave;me volet n&#039;est pas le fruit des recherches de Yoshinori Ono, le p&egrave;re fondateur de licence. En effet, c&#039;est une &eacute;quipe cr&eacute;ative originale compos&eacute;e de Yusuke Hashimoto (producteur de Bayonetta et r&eacute;alisateur de Bayonetta 2) et Kazuhiro Tsuchiya (producteur sur l&#039;ensemble des jeux Street Fighter) qui s&#039;est attel&eacute;e &agrave; la cr&eacute;ation du jeu.\r\n', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/g8WASSG5NA0\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>', 'street.jpg'),
(25, 'Tekken 8', 'combat', 'Playstation, Xbox &amp; PC', '2023', 'Comme annonc&eacute; dans l&#039;&eacute;pilogue de TEKKEN 7, ce nouvel opus sera centr&eacute; sur le combat entre p&egrave;re et fils, opposant Kazuya Mishima et Jin Kazama. TEKKEN 8 nous replonge dans le r&eacute;cit tragique des familles Mishima et Kazama, o&ugrave; les ranc&oelig;urs familiales donnent lieu &agrave; de nouveaux combats d&#039;anthologie.\r\n', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/0e4c5zWBdzk\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>', 'tekken.png'),
(26, 'Diablo IV', 'rpg', 'Playstation, Xbox &amp; PC', '2023', 'Comme les autres jeux de la s&eacute;rie, Diablo IV est un jeu hack &#039;n&#039; slash. L&#039;objectif pour le joueur est de contr&ocirc;ler un personnage qui doit explorer diff&eacute;rents environnements et combattre des monstres pour gagner de l&#039;exp&eacute;rience, des armes et divers objets d&#039;&eacute;quipement. L&#039;action du jeu se d&eacute;roule en temps r&eacute;el.\r\n', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/PnJtO7_B8EI\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>', 'diablo.jpg'),
(27, 'Final Fantasy XVI', 'rpg', 'Playstation', 'été 2023', 'Final Fantasy XVI prend place dans le monde de Valisth&eacute;a, dont la sp&eacute;cificit&eacute; est de contenir six cristaux, appel&eacute;s Cristaux-m&egrave;res, produisant de l&#039;&eacute;ther et permettant aux personnes vivant &agrave; proximit&eacute; d&#039;utiliser de la magie.\r\n', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/64eEnplElXA\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>', 'ff16.jpg'),
(28, 'Forspoken', 'rpg', 'Playstation &amp; PC', '24/01/23', 'Athia &eacute;tait autrefois un royaume prosp&egrave;re gouvern&eacute; par les thantas, des matriarches bienveillantes qui ont &eacute;t&eacute; d&eacute;plac&eacute;es par une peste d&eacute;vastatrice qui a tout corrompu sur son passage. Il s&rsquo;agit de The Tear, un fl&eacute;au qui a transform&eacute; les animaux en b&ecirc;tes et les &ecirc;tres humains en monstres. Autrefois sages et justes, les thanas se sont transform&eacute;es en sorci&egrave;res mal&eacute;fiques.\r\n', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/L2rqSXsIu1I\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>', 'forspoken.jpg'),
(29, 'GrandBlue Frantasy: Relink', 'rpg', 'Playstation, Xbox &amp; PC', '2023', 'Peu apr&egrave;s les &eacute;v&eacute;nements de Phantagrande, le lien vital qui unissait Gran &agrave; Lyria s&#039;est rompu, plongeant le premier dans un profond sommeil. Le jeu propose ainsi d&#039;incarner Katalina, l&#039;h&eacute;ro&iuml;ne principale, aux c&ocirc;t&eacute;s de Io, Rackham, Percival et leurs compagnons, qui se mirent en qu&ecirc;te de r&eacute;tablir ce lien \r\n', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/VwA88uXvz04\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>', 'grandblue.jpg'),
(30, 'One Piece Odyssey', 'rpg', 'Playstation, Xbox &amp; PC', '13/01/23', 'Au cours de leur p&eacute;riple sur Grand Line, le capitaine Monkey D. Luffy et son &eacute;quipage sont soudainement happ&eacute;s par une temp&ecirc;te. Ils se retrouvent s&eacute;par&eacute;s les uns des autres, naufrag&eacute;s sur une myst&eacute;rieuse &icirc;le luxuriante du nom de Waford. L&#039;&eacute;quipage embarque alors pour une nouvelle &eacute;pop&eacute;e.\r\n', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/xVjlz2mvKW8\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>', 'onepiece.jpg'),
(31, 'Starfield', 'rpg', 'Xbox &amp; PC', '2023', 'Starfield est un jeu de science-fiction &agrave; vocation relativement r&eacute;aliste. Le producteur ex&eacute;cutif Todd Howard indique que l&#039;&eacute;quipe s&#039;est rendue dans les locaux de SpaceX pour apporter de l&#039;&laquo; authenticit&eacute; &raquo; au jeu. Il &eacute;voque par exemple la propulsion nucl&eacute;aire utilisant de l&#039;h&eacute;lium 3.\r\n', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/CKTjIEtPtOs\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>', 'star.webp'),
(32, 'Alaska Truck Simulator', 'simulation', 'Playstation, Xbox &amp; PC', '07/12/22', 'Mettez-vous dans la peau des camionneurs de l&#039;Alaska. Installez-vous aux commandes de machines colossales et bravez l&#039;un des environnements les plus rudes et les plus dangereux. Relevez le d&eacute;fi et tentez de survivre assez longtemps pour profiter pleinement de la beaut&eacute; sauvage de l&#039;Alaska.\r\n', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/uY5ahVd4PuE\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>', 'alaskan.jpg'),
(33, 'High Rise City', 'simulation', 'PC', '24/03/22', 'Highrise City est la prochaine &eacute;tape de l&rsquo;&eacute;volution des City Sims. D&eacute;couvrez une refonte moderne du genre enrichie par un syst&egrave;me &eacute;conomique complexe bas&eacute; sur la gestion de ressources. Highrise City combine deux genres d&rsquo;une nouvelle mani&egrave;re: le City Builder et la plus traditionnelle simulation de gestion d&rsquo;&eacute;conomie.\r\n', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/n8Md3iwpN_0\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>', 'highrise.webp'),
(34, 'Way of the Hunter', 'simulation', 'Playstation', '16/08/22', 'A 83 ans, Edith Moore est une femme pleine de regrets. Suite au d&eacute;c&egrave;s de son &eacute;poux, sa fille souhaite la placer dans une maison de retraite mais Edith a une bien meilleure id&eacute;e. Toute sa vie, elle a r&ecirc;v&eacute; en secret de partir &agrave; l&#039;aventure mais n&#039;a jamais os&eacute;.\r\n', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/V3hMmafg2kY\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>', 'hunter.jpg'),
(35, 'Kerbal Space Program 2', 'simulation', 'Playstation, Xbox &amp; PC', '24/02/23', 'Dans Kerbal Space Program 2, les technologies interstellaires ouvrent la route &agrave; quantit&eacute; de nouveaux syst&egrave;mes stellaires et corps c&eacute;lestes, chacun pr&eacute;sentant ses propres d&eacute;fis et poss&eacute;dant ses propres tr&eacute;sors secrets.\r\n', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/P_nj6wW6Gsc\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>', 'kerbal.jpg'),
(36, 'Sengoku Dynasty', 'simulation', 'PC', '2023', 'Sengoku Dynasty permet aux joueurs de d&eacute;couvrir un Japon tr&egrave;s sp&eacute;cifique et surtout &agrave; la fois ravag&eacute; par la famine mais aussi la guerre. Vous incarnerez un personnage qui semblait au tout d&eacute;part &ecirc;tre un simple paysan travaillant la terre dans sa ville.\r\n', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/kOFKQfCNR2k\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>', 'sengoku.jpg'),
(37, 'Wild West Dynasty', 'simulation', 'PC', '2022', 'Wild West Dynasty offre aux joueurs la possibilit&eacute; de d&eacute;couvrir un monde ouvert qui m&eacute;lange &agrave; la fois le jeu de r&ocirc;le mais aussi de la survie. L&#039;objectif sera de devenir le ma&icirc;tre du Far West en construisant un superbe ranch tout en &eacute;levant votre famille.\r\n', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/an-8tjy9MUA\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>', 'wildwest.jpg'),
(38, '2K23', 'sport', 'Playstation, Xbox, Nintendo &amp; PC', '08/09/22', 'Roi des simulations de basketball, NBA 2K nous pr&eacute;sente une nouvelle it&eacute;ration annuelle ce week-end. NBA 2K23 d&eacute;barque dans nos salons et nos bureaux pour nous inviter &agrave; d&eacute;couvrir une nouvelle saison de NBA haute en intensit&eacute;. \r\n', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/aHs9ZzO0fbM\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>', '2k23.jpg'),
(39, 'Blood Bowl 3', 'sport', 'Playstation, Xbox, Nintendo &amp; PC', '2022', 'Blood Bowl1 est un jeu de football am&eacute;ricain fantastique, &agrave; la fois jeu de figurines et jeu de soci&eacute;t&eacute;, cr&eacute;&eacute; par Jervis Johnson en 1987. L&#039;action se situe dans l&#039;univers de Warhammer Fantasy Battle, un monde m&eacute;di&eacute;val fantastique imagin&eacute; par la compagnie Games Workshop.\r\n', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/8yd-uF_ohQQ\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>', 'Blood-Bowl-3-mise-en-avant.jpg'),
(40, 'Fifa 23', 'sport', 'Playstation, Xbox, Nintendo &amp; PC', '27/09/22', 'Il s&#039;agit de la derni&egrave;re version du c&eacute;l&egrave;bre licence de football en collaboration avec la FIFA. FIFA 23 apporte des am&eacute;liorations techniques, de nouveaux modes et de nouveaux joueurs pour cr&eacute;er les &eacute;quipes de foot.\r\n', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/YhfjMiYV98o\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>', 'fifa.jpg'),
(41, 'Football Manager 2023', 'sport', 'Playstation, Xbox &amp; PC', '08/11/22', 'le jeu vid&eacute;o qui vous met dans la peau d&rsquo;un entra&icirc;neur de foot, sort son &eacute;dition 2023 le 8 novembre prochain\r\n', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/JukwllD1Tvk\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>', 'foot.jpg'),
(42, 'FunFit', 'sport', 'Nintendo', '2023', 'Battle League Football est le nouveau volet de la saga Mario Striker. Incarnez les personnages embl&eacute;matiques de la licence Super Mario Bros et affrontez vous dans des matchs de football endiabl&eacute;s.\r\n', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/XhqzEtiD6qw\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>', 'funfit.jpg'),
(43, 'Mario Stikers Battle League', 'sport', 'Nintendo', '10/06/22', 'Mario Strikers : Battle League Football est le nouveau volet de la saga Mario Striker. Incarnez les personnages embl&eacute;matiques de la licence Super Mario Bros et affrontez vous dans des matchs de football endiabl&eacute;s.', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/N1Ui4aMOOz8\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>', 'thumb-1920-1211078.jpg');

--
-- Index pour les tables déchargées
--

--
-- Index pour la table `repertoire`
--
ALTER TABLE `repertoire`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT pour les tables déchargées
--

--
-- AUTO_INCREMENT pour la table `repertoire`
--
ALTER TABLE `repertoire`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=45;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
